import { MOA, User } from './types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    fullName: 'Admin User',
    email: 'admin@neu.edu.ph',
    role: 'admin',
    canAddMoa: true,
    canEditMoa: true,
    canDeleteMoa: true,
    isBlocked: false,
  },
  {
    id: 'u2',
    fullName: 'Faculty Member',
    email: 'faculty@neu.edu.ph',
    role: 'faculty',
    canAddMoa: true,
    canEditMoa: true,
    canDeleteMoa: false,
    isBlocked: false,
  },
  {
    id: 'u3',
    fullName: 'Student User',
    email: 'student@neu.edu.ph',
    role: 'student',
    canAddMoa: false,
    canEditMoa: false,
    canDeleteMoa: false,
    isBlocked: false,
  },
];

export const mockMOAs: MOA[] = [
  {
    id: 'moa1',
    hteId: 'HTE-001',
    companyName: 'Global Tech Solutions',
    address: '123 Innovation Drive, Silicon Valley',
    contactPerson: 'John Smith',
    contactEmail: 'jsmith@globaltech.com',
    industryType: 'Technology',
    effectiveDate: '2024-01-15T10:00:00Z',
    expirationDate: '2025-01-15T10:00:00Z',
    college: 'College of Computer Studies',
    status: 'APPROVED: Signed by President',
    isDeleted: false,
    auditTrail: [
      {
        userId: 'admin-id',
        userName: 'Admin User',
        timestamp: '2024-01-15T10:00:00Z',
        operation: 'INSERT',
      },
    ],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'moa2',
    hteId: 'HTE-002',
    companyName: 'Healthy Eats Corp',
    address: '45 Market Street, Quezon City',
    contactPerson: 'Maria Clara',
    contactEmail: 'mclara@healthyeats.com',
    industryType: 'Food',
    effectiveDate: '2023-11-20T14:30:00Z',
    expirationDate: '2024-11-20T14:30:00Z',
    college: 'College of Arts and Sciences',
    status: 'PROCESSING: Sent to Legal',
    isDeleted: false,
    auditTrail: [
      {
        userId: 'admin-id',
        userName: 'Admin User',
        timestamp: '2023-11-20T14:30:00Z',
        operation: 'INSERT',
      },
    ],
    createdAt: '2023-11-20T14:30:00Z',
    updatedAt: '2023-11-20T14:30:00Z',
  },
];
